### ISSUE TITLE
Add a way to do parallel uploads to AWS

### ISSUE THREAD

**Issue by Siphonay** [Chronister/cybrespace-meta#1]
The current command only uses s3cmd which isn't able to do parallel uploads of files to AWS. This command permits it, and allows for the process to be much faster.

It is to be run in the ~/live/public/system/ directory.
`find -type f | cut -d"/" -f 2- | xargs -P 6 -I {} s3cmd --acl-public sync {} s3://donphan-social/$(echo {} | sed "s:public/system/\(.*\):\1:")`

What this command does is:
- lists all of the files with find
- removes "./" from find's input with 
- xargs transforms every line of the output into single s3cmd commands, with the -P option specifying the number of workers. 6 is a value that I empirically found to be the most optimal for my origin server with two cores. Since uploading a single file into s3 doesn't conserve its path, xargs's args are used again to specify the file's path to s3cmd in the adress, and cutting out the filename off of it.

**Comment by chr-1x** [comment]
Added
